language: python

python:
  - "3.8"

install:
  - pipenv install

script:
  - pipenv run python -m release.cli
  - find . -type f ! -iname "*.ics" -delete

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
