name: Generate calendar from Wikipedia
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'
jobs:
  calendar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        console: ['switch', 'xboxone', 'ps4']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install .
      - name: Build 🔧 (${{ matrix.console }})
        env:
          CONSOLE: ${{ matrix.console }}
        run: pipenv run python -m release.cli --output build ${CONSOLE}
      - name: Deploy 🚀
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
